# Generated by Django 3.2.3 on 2021-06-02 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210602_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='course_student', to=settings.AUTH_USER_MODEL, verbose_name='course_student'),
        ),
    ]
