# Generated by Django 3.2.3 on 2021-06-03 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='course_teacher', to=settings.AUTH_USER_MODEL, verbose_name='course_teacher'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True, verbose_name='solution')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions_homework', to='courses.homework', verbose_name='homework')),
            ],
        ),
        migrations.AlterField(
            model_name='mark',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_to_solution', to='courses.solution', verbose_name='homework'),
        ),
    ]
